// Workers module exports
export * from './layout/workers-layout.component';
export * from './pages/espaces-disponibles/espaces-disponibles.component';
export * from './pages/detail-espace/detail-espace.component';
export * from './pages/reservation/reservation.component';
export * from './pages/paiement/paiement.component';
export * from './pages/confirmation/confirmation.component';
export * from './pages/mes-reservations/mes-reservations.component';
export * from './pages/historique-des-paiements/historique-des-paiements.component';
export * from './pages/historique-des-reservations/historique-des-reservations.component';
export * from './pages/messages/messages.component';
export * from './workers.routes';